In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

In [3]:
#  Import and read the all_data_merged.csv
fire_df = pd.read_csv("../Machine Learning Data/all_data_merged.csv")
fire_df

,County,Year,Name,County IDs,Latitude,Longitude,Started,Acres Burned,Cal Fire Incident,Major Incident,...,Avg Rel Hum (%),Dew Point (F),Avg Wind Speed (mph),Avg Soil Temp (F),MWh,Ocean Proximity,Population,Households,Average Income,Average House Value
0,Tuolumne,2013,Rim Fire,55,37.86,-120.09,2013-08-17 15:25:00+00:00,257314,t,f,...,61.117159,45.477952,4.918956,61.116300,460.72,INLAND,48456,17953,28035,124328
1,Los Angeles,2013,Powerhouse Fire,19,34.59,-118.42,2013-05-30 15:28:00+00:00,30274,t,f,...,51.038658,41.909835,4.157583,63.358755,68373.30,<1H OCEAN,8777895,2970038,43788,255083
2,Riverside,2013,Mountain Fire,33,33.71,-116.73,2013-07-15 13:43:00+00:00,27531,t,f,...,45.495943,43.821015,4.654100,66.373240,15138.42,<1H OCEAN,1159159,400110,34210,141866
3,Placer,2013,American Fire,31,39.12,-120.65,2013-08-10 16:30:00+00:00,27440,f,f,...,50.901685,42.369944,3.463462,62.848352,2877.46,INLAND,173793,64326,39368,172386
4,Ventura,2013,Springs Fire,56,0.00,0.00,2013-05-02 07:01:00+00:00,24251,t,t,...,66.377747,47.476236,3.760852,64.026648,5397.69,<1H OCEAN,663408,215793,47464,261187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Riverside,2019,Eagle Fire,33,33.83,-117.50,2019-10-10 12:08:00+00:00,9,t,f,...,50.044884,45.434651,4.407507,64.942880,15520.13,<1H OCEAN,1159159,400110,34210,141866
1569,Nevada,2019,Long Fire,29,39.41,-121.00,2019-06-28 15:03:04+00:00,2,t,f,...,58.371901,45.271350,3.355647,65.803030,712.54,INLAND,78510,30747,32913,150322
1570,Yolo,2019,Cashe Fire,57,38.73,-121.73,2019-11-25 12:02:02+00:00,0,f,f,...,61.942113,46.525904,5.039653,61.044718,1720.75,INLAND,138342,49868,30126,140261
1571,San Diego,2019,Oak Fire,37,33.35,-117.40,2019-10-22 19:20:44+00:00,0,f,f,...,67.014949,50.516284,3.311906,65.816017,19047.67,<1H OCEAN,2444026,882162,41120,208943
1572,Riverside,2019,Johnson Fire,33,33.45,-116.06,2019-10-14 15:32:20+00:00,0,f,f,...,50.044884,45.434651,4.407507,64.942880,15520.13,<1H OCEAN,1159159,400110,34210,141866

In [4]:
# Convert the 'f' to False and 't' to True in Major Incident column
fire_df["Major Incident"] = fire_df["Major Incident"].replace('f', 'False')
fire_df["Major Incident"] = fire_df["Major Incident"].replace('t', 'True')
fire_df["Major Incident"]

0       False
1       False
2       False
3       False
4        True
        ...
1568    False
1569    False
1570    False
1571    False
1572    False
Name: Major Incident, Length: 1573, dtype: object

In [5]:
# Encode Major Incident column so that it is in integer format
fire_df = pd.get_dummies(fire_df, columns=["Major Incident"])
fire_df.head()

,County,Year,Name,County IDs,Latitude,Longitude,Started,Acres Burned,Cal Fire Incident,ETo (in),...,Avg Wind Speed (mph),Avg Soil Temp (F),MWh,Ocean Proximity,Population,Households,Average Income,Average House Value,Major Incident_False,Major Incident_True
0,Tuolumne,2013,Rim Fire,55,37.86,-120.09,2013-08-17 15:25:00+00:00,257314,t,174.53,...,4.918956,61.116300,460.72,INLAND,48456,17953,28035,124328,1,0
1,Los Angeles,2013,Powerhouse Fire,19,34.59,-118.42,2013-05-30 15:28:00+00:00,30274,t,585.57,...,4.157583,63.358755,68373.30,<1H OCEAN,8777895,2970038,43788,255083,1,0
2,Riverside,2013,Mountain Fire,33,33.71,-116.73,2013-07-15 13:43:00+00:00,27531,t,705.76,...,4.654100,66.373240,15138.42,<1H OCEAN,1159159,400110,34210,141866,1,0
3,Placer,2013,American Fire,31,39.12,-120.65,2013-08-10 16:30:00+00:00,27440,f,56.38,...,3.463462,62.848352,2877.46,INLAND,173793,64326,39368,172386,1,0
4,Ventura,2013,Springs Fire,56,0.00,0.00,2013-05-02 07:01:00+00:00,24251,t,104.11,...,3.760852,64.026648,5397.69,<1H OCEAN,663408,215793,47464,261187,0,1

In [6]:
# Keep the encoded Major Incident column where False=0 and True=1
fire_df = fire_df.drop(columns=["Major Incident_False"])
fire_df.head()

,County,Year,Name,County IDs,Latitude,Longitude,Started,Acres Burned,Cal Fire Incident,ETo (in),...,Dew Point (F),Avg Wind Speed (mph),Avg Soil Temp (F),MWh,Ocean Proximity,Population,Households,Average Income,Average House Value,Major Incident_True
0,Tuolumne,2013,Rim Fire,55,37.86,-120.09,2013-08-17 15:25:00+00:00,257314,t,174.53,...,45.477952,4.918956,61.116300,460.72,INLAND,48456,17953,28035,124328,0
1,Los Angeles,2013,Powerhouse Fire,19,34.59,-118.42,2013-05-30 15:28:00+00:00,30274,t,585.57,...,41.909835,4.157583,63.358755,68373.30,<1H OCEAN,8777895,2970038,43788,255083,0
2,Riverside,2013,Mountain Fire,33,33.71,-116.73,2013-07-15 13:43:00+00:00,27531,t,705.76,...,43.821015,4.654100,66.373240,15138.42,<1H OCEAN,1159159,400110,34210,141866,0
3,Placer,2013,American Fire,31,39.12,-120.65,2013-08-10 16:30:00+00:00,27440,f,56.38,...,42.369944,3.463462,62.848352,2877.46,INLAND,173793,64326,39368,172386,0
4,Ventura,2013,Springs Fire,56,0.00,0.00,2013-05-02 07:01:00+00:00,24251,t,104.11,...,47.476236,3.760852,64.026648,5397.69,<1H OCEAN,663408,215793,47464,261187,1

In [7]:
# fire_df = fire_df.rename(columns={"Major Incident_True":"Major Incident"}, inplace=True)

In [8]:
# Checking data types
fire_df.dtypes

County                   object
Year                      int64
Name                     object
County IDs                int64
Latitude                float64
Longitude               float64
Started                  object
Acres Burned              int64
Cal Fire Incident        object
ETo (in)                float64
Precip (in)             float64
Sol Rad (Ly/day)        float64
Avg Vap Pres (mBars)    float64
Max Air Temp (F)        float64
Min Air Temp (F)        float64
Avg Air Temp (F)        float64
Max Rel Hum (%)           int64
Min Rel Hum (%)           int64
Avg Rel Hum (%)         float64
Dew Point (F)           float64
Avg Wind Speed (mph)    float64
Avg Soil Temp (F)       float64
MWh                     float64
Ocean Proximity          object
Population                int64
Households                int64
Average Income            int64
Average House Value       int64
Major Incident_True       uint8
dtype: object

In [9]:
# Drop the non-beneficial ID columns, 'Name'.
fire_df = fire_df.drop(columns=["Name", "Started"])

fire_df

,County,Year,County IDs,Latitude,Longitude,Acres Burned,Cal Fire Incident,ETo (in),Precip (in),Sol Rad (Ly/day),...,Dew Point (F),Avg Wind Speed (mph),Avg Soil Temp (F),MWh,Ocean Proximity,Population,Households,Average Income,Average House Value,Major Incident_True
0,Tuolumne,2013,55,37.86,-120.09,257314,t,174.53,10.54,451.219780,...,45.477952,4.918956,61.116300,460.72,INLAND,48456,17953,28035,124328,0
1,Los Angeles,2013,19,34.59,-118.42,30274,t,585.57,40.28,448.643428,...,41.909835,4.157583,63.358755,68373.30,<1H OCEAN,8777895,2970038,43788,255083,0
2,Riverside,2013,33,33.71,-116.73,27531,t,705.76,29.75,462.865524,...,43.821015,4.654100,66.373240,15138.42,<1H OCEAN,1159159,400110,34210,141866,0
3,Placer,2013,31,39.12,-120.65,27440,f,56.38,5.70,429.434066,...,42.369944,3.463462,62.848352,2877.46,INLAND,173793,64326,39368,172386,0
4,Ventura,2013,56,0.00,0.00,24251,t,104.11,6.92,429.200549,...,47.476236,3.760852,64.026648,5397.69,<1H OCEAN,663408,215793,47464,261187,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Riverside,2019,33,33.83,-117.50,9,t,672.13,98.83,473.761688,...,45.434651,4.407507,64.942880,15520.13,<1H OCEAN,1159159,400110,34210,141866,0
1569,Nevada,2019,29,39.41,-121.00,2,t,50.84,38.35,402.173554,...,45.271350,3.355647,65.803030,712.54,INLAND,78510,30747,32913,150322,0
1570,Yolo,2019,57,38.73,-121.73,0,f,103.37,52.17,423.879884,...,46.525904,5.039653,61.044718,1720.75,INLAND,138342,49868,30126,140261,0
1571,San Diego,2019,37,33.35,-117.40,0,f,264.88,88.22,454.233316,...,50.516284,3.311906,65.816017,19047.67,<1H OCEAN,2444026,882162,41120,208943,0
1572,Riverside,2019,33,33.45,-116.06,0,f,672.13,98.83,473.761688,...,45.434651,4.407507,64.942880,15520.13,<1H OCEAN,1159159,400110,34210,141866,0

In [10]:
# Determine the number of unique values in each column.
fire_df.nunique()

County                   55
Year                      7
County IDs               55
Latitude                716
Longitude               581
Acres Burned            616
Cal Fire Incident         2
ETo (in)                253
Precip (in)             255
Sol Rad (Ly/day)        256
Avg Vap Pres (mBars)    256
Max Air Temp (F)        142
Min Air Temp (F)        150
Avg Air Temp (F)        256
Max Rel Hum (%)           6
Min Rel Hum (%)          23
Avg Rel Hum (%)         256
Dew Point (F)           256
Avg Wind Speed (mph)    256
Avg Soil Temp (F)       256
MWh                     313
Ocean Proximity           3
Population               55
Households               55
Average Income           55
Average House Value      55
Major Incident_True       2
dtype: int64

In [11]:
# Generate our categorical variable lists
fire_cat = fire_df.dtypes[fire_df.dtypes == "object"].index.tolist()

fire_cat

['County', 'Cal Fire Incident', 'Ocean Proximity']

In [12]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(fire_df[fire_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(fire_cat)
encode_df.head()

,County_Alameda,County_Alpine,County_Amador,County_Butte,County_Calaveras,County_Colusa,County_Contra Costa,County_El Dorado,County_Fresno,County_Glenn,...,County_Tulare,County_Tuolumne,County_Ventura,County_Yolo,County_Yuba,Cal Fire Incident_f,Cal Fire Incident_t,Ocean Proximity_<1H OCEAN,Ocean Proximity_INLAND,Ocean Proximity_NEAR BAY
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [13]:
# Merge one-hot encoded features and drop the originals
fire_df = fire_df.merge(encode_df,left_index=True, right_index=True)
fire_df = fire_df.drop(fire_cat,1)
fire_df

,Year,County IDs,Latitude,Longitude,Acres Burned,ETo (in),Precip (in),Sol Rad (Ly/day),Avg Vap Pres (mBars),Max Air Temp (F),...,County_Tulare,County_Tuolumne,County_Ventura,County_Yolo,County_Yuba,Cal Fire Incident_f,Cal Fire Incident_t,Ocean Proximity_<1H OCEAN,Ocean Proximity_INLAND,Ocean Proximity_NEAR BAY
0,2013,55,37.86,-120.09,257314,174.53,10.54,451.219780,10.936722,104.1,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,2013,19,34.59,-118.42,30274,585.57,40.28,448.643428,10.350647,110.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,2013,33,33.71,-116.73,27531,705.76,29.75,462.865524,10.856196,119.7,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,2013,31,39.12,-120.65,27440,56.38,5.70,429.434066,9.842308,106.6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,2013,56,0.00,0.00,24251,104.11,6.92,429.200549,12.061126,96.1,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,2019,33,33.83,-117.50,9,672.13,98.83,473.761688,11.150334,123.7,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1569,2019,29,39.41,-121.00,2,50.84,38.35,402.173554,10.727824,103.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1570,2019,57,38.73,-121.73,0,103.37,52.17,423.879884,11.326339,106.7,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1571,2019,37,33.35,-117.40,0,264.88,88.22,454.233316,13.359156,114.9,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1572,2019,33,33.45,-116.06,0,672.13,98.83,473.761688,11.150334,123.7,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [14]:
# Split our preprocessed data into our features and target arrays
y = fire_df["Major Incident_True"].values
X = fire_df.drop(columns=["Major Incident_True"], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  3
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 3)                 252
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 20
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 278
Trainable params: 278
Non-trainable params: 0
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=20)

Epoch 1/20
37/37 [==============================] - 1s 927us/step - loss: 0.6126 - accuracy: 0.7608
Epoch 2/20
37/37 [==============================] - 0s 871us/step - loss: 0.5814 - accuracy: 0.7608
Epoch 3/20
37/37 [==============================] - 0s 1ms/step - loss: 0.5605 - accuracy: 0.7608
Epoch 4/20
37/37 [==============================] - 0s 823us/step - loss: 0.5464 - accuracy: 0.7608
Epoch 5/20
37/37 [==============================] - 0s 837us/step - loss: 0.5349 - accuracy: 0.7608
Epoch 6/20
37/37 [==============================] - 0s 811us/step - loss: 0.5251 - accuracy: 0.7608
Epoch 7/20
37/37 [==============================] - 0s 755us/step - loss: 0.5163 - accuracy: 0.7608
Epoch 8/20
37/37 [==============================] - 0s 758us/step - loss: 0.5085 - accuracy: 0.7608
Epoch 9/20
37/37 [==============================] - 0s 771us/step - loss: 0.5021 - accuracy: 0.7608
Epoch 10/20
37/37 [==============================] - 0s 811us/step - loss: 0.4954 - accuracy: 0.7608
Epoch 11/20
37/37 [==============================] - 0s 816us/step - loss: 0.4902 - accuracy: 0.7608
Epoch 12/20
37/37 [==============================] - 0s 790us/step - loss: 0.4850 - accuracy: 0.7608
Epoch 13/20
37/37 [==============================] - 0s 794us/step - loss: 0.4807 - accuracy: 0.7608
Epoch 14/20
37/37 [==============================] - 0s 773us/step - loss: 0.4763 - accuracy: 0.7608
Epoch 15/20
37/37 [==============================] - 0s 854us/step - loss: 0.4728 - accuracy: 0.7608
Epoch 16/20
37/37 [==============================] - 0s 756us/step - loss: 0.4694 - accuracy: 0.7608
Epoch 17/20
37/37 [==============================] - 0s 767us/step - loss: 0.4661 - accuracy: 0.7608
Epoch 18/20
37/37 [==============================] - 0s 819us/step - loss: 0.4631 - accuracy: 0.7608
Epoch 19/20
37/37 [==============================] - 0s 844us/step - loss: 0.4599 - accuracy: 0.7608
Epoch 20/20
37/37 [==============================] - 0s 815us/step - loss: 0.4574 - accuracy: 0.7608

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

13/13 - 0s - loss: 0.4896 - accuracy: 0.7919
Loss: 0.48958906531333923, Accuracy: 0.7918781638145447

In [ ]:
# # get importance
# importance = fit_model.coef_
# # summarize feature importance
# for i,v in enumerate(importance):
# 	print('Feature: %0d, Score: %.5f' % (i,v))
# # plot feature importance
# pyplot.bar([x for x in range(len(importance))], importance)
# pyplot.show()

# Trying out Logistic Regression Model (Just in Case)

In [20]:
y = fire_df["Major Incident_True"]
X = fire_df.drop(columns="Major Incident_True")

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(1179, 83)

In [22]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=1000,
                                random_state=1)

In [23]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=1)

In [24]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            0       0
2            0       0
3            0       1
4            0       0
5            0       0
6            0       0
7            0       0
8            0       0
9            0       0
10           0       0
11           0       0
12           0       1
13           0       0
14           0       1
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [25]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7715736040609137

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

In [27]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[300   3]
 [ 87   4]]

In [28]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.99      0.87       303
           1       0.57      0.04      0.08        91

    accuracy                           0.77       394
   macro avg       0.67      0.52      0.48       394
weighted avg       0.73      0.77      0.69       394

In [ ]:
# # get importance
# importance = fit_model.coef_
# # summarize feature importance
# for i,v in enumerate(importance):
# 	print('Feature: %0d, Score: %.5f' % (i,v))
# # plot feature importance
# pyplot.bar([x for x in range(len(importance))], importance)
# pyplot.show()